import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Configuração da fonte Poppins com várias espessuras
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Metadados da aplicação Next.js (SEO, título, descrição, etc.)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout raiz que envolve toda a aplicação
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Retorna a estrutura HTML com a fonte aplicada e o conteúdo filho renderizado
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
